# Generated by Django 5.2.3 on 2025-06-11 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("empresa", models.CharField(max_length=150, unique=True)),
                ("endereco_rua", models.CharField(max_length=150)),
                ("endereco_numero", models.CharField(max_length=150)),
                ("endereco_estado", models.CharField(max_length=150)),
                ("endereco_cidade", models.CharField(max_length=150)),
                ("endereco_cep", models.CharField(max_length=150)),
                ("razao_social", models.CharField(max_length=150)),
                ("cnpj", models.CharField(max_length=30, unique=True)),
                ("distribuidora", models.CharField(max_length=150)),
                ("modalidade_tarifaria", models.CharField(max_length=20)),
                ("consumo_ponta_kwh", models.FloatField(blank=True, null=True)),
                ("consumo_fora_ponta_kwh", models.FloatField(blank=True, null=True)),
                ("valor_medio_fatura", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
