# Generated by Django 5.2.3 on 2025-06-11 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="gestor_responsavel_fk",
            field=models.ForeignKey(
                blank=True,
                db_column="gestor_responsavel_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empresas_geridas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
